version: "3"

services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1

    visualizations:
        build:
            context: ./visualizations
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        environment:
            PORT: 8080
            FLASK_DEBUG: 1

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "4200:4200"
